/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface DeleteCategoryApiCategoriesCategoryIdDelete$Params {
  category_id: string;
}

export function deleteCategoryApiCategoriesCategoryIdDelete(http: HttpClient, rootUrl: string, params: DeleteCategoryApiCategoriesCategoryIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, deleteCategoryApiCategoriesCategoryIdDelete.PATH, 'delete');
  if (params) {
    rb.path('category_id', params.category_id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

deleteCategoryApiCategoriesCategoryIdDelete.PATH = '/api/categories/{category_id}';
