/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CategoryResponse } from '../../models/category-response';
import { CategoryUpdate } from '../../models/category-update';

export interface UpdateCategoryApiCategoriesCategoryIdPut$Params {
  category_id: number;
  current_user?: any;
      body: CategoryUpdate
}

export function updateCategoryApiCategoriesCategoryIdPut(http: HttpClient, rootUrl: string, params: UpdateCategoryApiCategoriesCategoryIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<CategoryResponse>> {
  const rb = new RequestBuilder(rootUrl, updateCategoryApiCategoriesCategoryIdPut.PATH, 'put');
  if (params) {
    rb.path('category_id', params.category_id, {});
    rb.query('current_user', params.current_user, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CategoryResponse>;
    })
  );
}

updateCategoryApiCategoriesCategoryIdPut.PATH = '/api/categories/{category_id}';
