/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AiSettingsResponse } from '../../models/ai-settings-response';

export interface ReadAiSettingsApiAiSettingsGet$Params {
}

export function readAiSettingsApiAiSettingsGet(http: HttpClient, rootUrl: string, params?: ReadAiSettingsApiAiSettingsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<AiSettingsResponse>> {
  const rb = new RequestBuilder(rootUrl, readAiSettingsApiAiSettingsGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AiSettingsResponse>;
    })
  );
}

readAiSettingsApiAiSettingsGet.PATH = '/api/ai-settings/';
