/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AiSettingsResponse } from '../../models/ai-settings-response';
import { AiSettingsUpdate } from '../../models/ai-settings-update';

export interface UpdateAiSettingsApiAiSettingsPut$Params {
      body: AiSettingsUpdate
}

export function updateAiSettingsApiAiSettingsPut(http: HttpClient, rootUrl: string, params: UpdateAiSettingsApiAiSettingsPut$Params, context?: HttpContext): Observable<StrictHttpResponse<AiSettingsResponse>> {
  const rb = new RequestBuilder(rootUrl, updateAiSettingsApiAiSettingsPut.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AiSettingsResponse>;
    })
  );
}

updateAiSettingsApiAiSettingsPut.PATH = '/api/ai-settings/';
