/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AiSettingsUpdate {
  classifier_base_url?: (string | null);
  classifier_model?: (string | null);
  classifier_provider?: (string | null);
  responder_base_url?: (string | null);
  responder_model?: (string | null);
  responder_provider?: (string | null);
}
