/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AISettingsUpdate {
  classifier_provider?: string | null;
  classifier_model?: string | null;
  classifier_base_url?: string | null;
  responder_provider?: string | null;
  responder_model?: string | null;
  responder_base_url?: string | null;
}