/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AISettingsResponse {
  id: string;
  classifier_provider: string;
  classifier_model: string;
  classifier_base_url?: string | null;
  responder_provider: string;
  responder_model: string;
  responder_base_url?: string | null;
}