/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BodyUploadDocumentApiDocumentsUploadPost {
  category_ids?: (Array<string> | null);
  file?: (string | null);
  url?: (string | null);
}
