/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CategoryCreate {
  description?: (string | null);

  /**
   * Nome univoco della categoria
   */
  name: string;
}
