/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CategoryResponse } from '../models/category-response';
export interface DocumentResponse {
  category?: (CategoryResponse | null);
  category_id?: (string | null);
  content_type: string;
  extracted_text?: (string | null);
  filename: string;
  id: string;
  link?: (string | null);
}
