/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EmailStatus } from './email-status';

/**
 * Each possible value of `EmailStatus`
 */
export const EMAIL_STATUS: EmailStatus[] = [
  'UNREAD',
  'TO_CLASSIFY',
  'TO_RESPOND',
  'DRAFT',
  'ESCALATED',
  'SENT',
  'IGNORED',
  'FAILED'
];