/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FeedbackResponse {
  created_at: string;
  description: string;
  id: string;
  image_path?: (string | null);
  updated_at: string;
  user_id: string;
}
