/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CategoryResponse } from '../models/category-response';
import { TemplateStatus } from '../models/template-status';
export interface TemplateResponse {
  body_template: string;
  categories?: Array<CategoryResponse>;
  id: string;
  name: string;
  status: TemplateStatus;
  subject_template?: (string | null);
  usage_count: number;
}
