/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TemplateCreate {
  body_template: string;
  category_ids?: Array<string>;
  name: string;
  subject_template?: (string | null);
}
