/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EmailResponse } from '../../models/email-response';
import { EmailStatus } from '../../models/email-status';

export interface ReadEmailsApiEmailsGet$Params {
  status?: (EmailStatus | null);
  skip?: number;
  limit?: number;
}

export function readEmailsApiEmailsGet(http: HttpClient, rootUrl: string, params?: ReadEmailsApiEmailsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<EmailResponse>>> {
  const rb = new RequestBuilder(rootUrl, readEmailsApiEmailsGet.PATH, 'get');
  if (params) {
    rb.query('status', params.status, {});
    rb.query('skip', params.skip, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<EmailResponse>>;
    })
  );
}

readEmailsApiEmailsGet.PATH = '/api/emails/';
