"""add_status_and_usage_count_to_templates

Revision ID: 48f741ad452f
Revises: 556f5d2f2745
Create Date: 2026-06-19 18:19:43.211205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48f741ad452f'
down_revision = '556f5d2f2745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
