"""add_users_table

Revision ID: 96dafdbbf25c
Revises: 48f741ad452f
Create Date: 2026-06-19 18:31:46.114096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96dafdbbf25c'
down_revision = '48f741ad452f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
