/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TemplateCreate } from '../../models/template-create';
import { TemplateResponse } from '../../models/template-response';

export interface CreateTemplateApiTemplatesPost$Params {
  current_user?: any;
      body: TemplateCreate
}

export function createTemplateApiTemplatesPost(http: HttpClient, rootUrl: string, params: CreateTemplateApiTemplatesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<TemplateResponse>> {
  const rb = new RequestBuilder(rootUrl, createTemplateApiTemplatesPost.PATH, 'post');
  if (params) {
    rb.query('current_user', params.current_user, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TemplateResponse>;
    })
  );
}

createTemplateApiTemplatesPost.PATH = '/api/templates/';
