/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface DeleteTemplateApiTemplatesTemplateIdDelete$Params {
  template_id: number;
}

export function deleteTemplateApiTemplatesTemplateIdDelete(http: HttpClient, rootUrl: string, params: DeleteTemplateApiTemplatesTemplateIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, deleteTemplateApiTemplatesTemplateIdDelete.PATH, 'delete');
  if (params) {
    rb.path('template_id', params.template_id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

deleteTemplateApiTemplatesTemplateIdDelete.PATH = '/api/templates/{template_id}';
