/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TemplateResponse } from '../../models/template-response';

export interface ReadPendingTemplatesApiTemplatesPendingGet$Params {
}

export function readPendingTemplatesApiTemplatesPendingGet(http: HttpClient, rootUrl: string, params?: ReadPendingTemplatesApiTemplatesPendingGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TemplateResponse>>> {
  const rb = new RequestBuilder(rootUrl, readPendingTemplatesApiTemplatesPendingGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TemplateResponse>>;
    })
  );
}

readPendingTemplatesApiTemplatesPendingGet.PATH = '/api/templates/pending';
