/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TemplateResponse } from '../../models/template-response';

export interface ReadTemplatesApiTemplatesGet$Params {
  skip?: number;
  limit?: number;
}

export function readTemplatesApiTemplatesGet(http: HttpClient, rootUrl: string, params?: ReadTemplatesApiTemplatesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TemplateResponse>>> {
  const rb = new RequestBuilder(rootUrl, readTemplatesApiTemplatesGet.PATH, 'get');
  if (params) {
    rb.query('skip', params.skip, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TemplateResponse>>;
    })
  );
}

readTemplatesApiTemplatesGet.PATH = '/api/templates/';
