/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TemplateResponse } from '../../models/template-response';
import { TemplateUpdate } from '../../models/template-update';

export interface UpdateTemplateApiTemplatesTemplateIdPut$Params {
  template_id: string;
      body: TemplateUpdate
}

export function updateTemplateApiTemplatesTemplateIdPut(http: HttpClient, rootUrl: string, params: UpdateTemplateApiTemplatesTemplateIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<TemplateResponse>> {
  const rb = new RequestBuilder(rootUrl, updateTemplateApiTemplatesTemplateIdPut.PATH, 'put');
  if (params) {
    rb.path('template_id', params.template_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TemplateResponse>;
    })
  );
}

updateTemplateApiTemplatesTemplateIdPut.PATH = '/api/templates/{template_id}';
