/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BodyCreateUserFeedbackApiFeedbackPost } from '../../models/body-create-user-feedback-api-feedback-post';
import { FeedbackResponse } from '../../models/feedback-response';

export interface CreateUserFeedbackApiFeedbackPost$Params {
      body: BodyCreateUserFeedbackApiFeedbackPost
}

export function createUserFeedbackApiFeedbackPost(http: HttpClient, rootUrl: string, params: CreateUserFeedbackApiFeedbackPost$Params, context?: HttpContext): Observable<StrictHttpResponse<FeedbackResponse>> {
  const rb = new RequestBuilder(rootUrl, createUserFeedbackApiFeedbackPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FeedbackResponse>;
    })
  );
}

createUserFeedbackApiFeedbackPost.PATH = '/api/feedback/';
