/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DocumentResponse } from '../../models/document-response';
import { DocumentUpdate } from '../../models/document-update';

export interface UpdateDocumentApiDocumentsDocumentIdPut$Params {
  document_id: string;
      body: DocumentUpdate
}

export function updateDocumentApiDocumentsDocumentIdPut(http: HttpClient, rootUrl: string, params: UpdateDocumentApiDocumentsDocumentIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<DocumentResponse>> {
  const rb = new RequestBuilder(rootUrl, updateDocumentApiDocumentsDocumentIdPut.PATH, 'put');
  if (params) {
    rb.path('document_id', params.document_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DocumentResponse>;
    })
  );
}

updateDocumentApiDocumentsDocumentIdPut.PATH = '/api/documents/{document_id}';
