/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BodyUploadDocumentApiDocumentsUploadPost } from '../../models/body-upload-document-api-documents-upload-post';
import { DocumentResponse } from '../../models/document-response';

export interface UploadDocumentApiDocumentsUploadPost$Params {
      body?: BodyUploadDocumentApiDocumentsUploadPost
}

export function uploadDocumentApiDocumentsUploadPost(http: HttpClient, rootUrl: string, params?: UploadDocumentApiDocumentsUploadPost$Params, context?: HttpContext): Observable<StrictHttpResponse<DocumentResponse>> {
  const rb = new RequestBuilder(rootUrl, uploadDocumentApiDocumentsUploadPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DocumentResponse>;
    })
  );
}

uploadDocumentApiDocumentsUploadPost.PATH = '/api/documents/upload';
