/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BodyUploadDocumentApiDocumentsUploadPost {
  category_id?: (number | null);
  file?: (string | null);
  url?: (string | null);
}
