/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CategoryResponse {
  description?: (string | null);
  id: string;

  /**
   * Nome univoco della categoria
   */
  name: string;
}
