/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EmailStatus } from '../models/email-status';
export interface EmailUpdateDraft {
  generated_draft: string;
  status: EmailStatus;
}
