/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EmailCreate {
  body?: (string | null);
  category_ids?: Array<string>;
  gmail_id: string;
  sender: string;
  subject?: (string | null);
}
