/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TemplateUpdate {
  body_template?: (string | null);
  category_ids?: (Array<string> | null);
  name?: (string | null);
  subject_template?: (string | null);
}
