/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserRole } from '../models/user-role';
export interface UserResponse {
  email: string;
  id: string;
  is_active: boolean;
  role: UserRole;
}
