/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TokenResponse } from '../../models/token-response';

export interface RefreshAccessTokenApiAuthRefreshPost$Params {
  refresh_token: string;
}

export function refreshAccessTokenApiAuthRefreshPost(http: HttpClient, rootUrl: string, params: RefreshAccessTokenApiAuthRefreshPost$Params, context?: HttpContext): Observable<StrictHttpResponse<TokenResponse>> {
  const rb = new RequestBuilder(rootUrl, refreshAccessTokenApiAuthRefreshPost.PATH, 'post');
  if (params) {
    rb.query('refresh_token', params.refresh_token, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TokenResponse>;
    })
  );
}

refreshAccessTokenApiAuthRefreshPost.PATH = '/api/auth/refresh';
