/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserCreate } from '../../models/user-create';
import { UserResponse } from '../../models/user-response';

export interface RegisterApiAuthRegisterPost$Params {
  current_user?: any;
      body: UserCreate
}

export function registerApiAuthRegisterPost(http: HttpClient, rootUrl: string, params: RegisterApiAuthRegisterPost$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponse>> {
  const rb = new RequestBuilder(rootUrl, registerApiAuthRegisterPost.PATH, 'post');
  if (params) {
    rb.query('current_user', params.current_user, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserResponse>;
    })
  );
}

registerApiAuthRegisterPost.PATH = '/api/auth/register';
