/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface LogoutApiAuthLogoutPost$Params {
  Authorization?: (string | null);
  'X-Refresh-Token'?: (string | null);
}

export function logoutApiAuthLogoutPost(http: HttpClient, rootUrl: string, params?: LogoutApiAuthLogoutPost$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, logoutApiAuthLogoutPost.PATH, 'post');
  if (params) {
    rb.header('Authorization', params.Authorization, {});
    rb.header('X-Refresh-Token', params['X-Refresh-Token'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

logoutApiAuthLogoutPost.PATH = '/api/auth/logout';
