/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TokenRefreshRequest } from '../../models/token-refresh-request';
import { TokenResponse } from '../../models/token-response';

export interface RefreshAccessTokenApiAuthRefreshPost$Params {
      body: TokenRefreshRequest
}

export function refreshAccessTokenApiAuthRefreshPost(http: HttpClient, rootUrl: string, params: RefreshAccessTokenApiAuthRefreshPost$Params, context?: HttpContext): Observable<StrictHttpResponse<TokenResponse>> {
  const rb = new RequestBuilder(rootUrl, refreshAccessTokenApiAuthRefreshPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TokenResponse>;
    })
  );
}

refreshAccessTokenApiAuthRefreshPost.PATH = '/api/auth/refresh';
