/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EmailCreate } from '../../models/email-create';
import { EmailResponse } from '../../models/email-response';

export interface CreateNewEmailApiEmailsPost$Params {
      body: EmailCreate
}

export function createNewEmailApiEmailsPost(http: HttpClient, rootUrl: string, params: CreateNewEmailApiEmailsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<EmailResponse>> {
  const rb = new RequestBuilder(rootUrl, createNewEmailApiEmailsPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EmailResponse>;
    })
  );
}

createNewEmailApiEmailsPost.PATH = '/api/emails/';
