/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EmailResponse } from '../../models/email-response';
import { EmailUpdateDraft } from '../../models/email-update-draft';

export interface UpdateEmailDraftApiEmailsEmailIdDraftPut$Params {
  email_id: number;
  current_user?: any;
      body: EmailUpdateDraft
}

export function updateEmailDraftApiEmailsEmailIdDraftPut(http: HttpClient, rootUrl: string, params: UpdateEmailDraftApiEmailsEmailIdDraftPut$Params, context?: HttpContext): Observable<StrictHttpResponse<EmailResponse>> {
  const rb = new RequestBuilder(rootUrl, updateEmailDraftApiEmailsEmailIdDraftPut.PATH, 'put');
  if (params) {
    rb.path('email_id', params.email_id, {});
    rb.query('current_user', params.current_user, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EmailResponse>;
    })
  );
}

updateEmailDraftApiEmailsEmailIdDraftPut.PATH = '/api/emails/{email_id}/draft';
